POST http://localhost:8080/api/question-compiler/696a376c0fb75495a73cd463/run
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhbWl0amFraGFyNzMwQGdtYWlsLmNvbSIsImlhdCI6MTc2OTE5NzgwOSwiZXhwIjoxNzY5Mjg0MjA5fQ.QuT36QKdgezcF0CWhNBPn4YJs-Qq5SaEnEgcp630IXoh5zgcY0FF_Gx5KaDPVL9JylN3GWrXWwb6rcni4EB-Kg

< ./request-body.json
